// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Camera
type Camera struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"displayName"`
	Protocol    CameraProtocol `json:"protocol"`
	Phase       CameraPhase    `json:"phase"`
	Endpoint    CameraEndpoint `json:"endpoint"`
	LiveKit     CameraLiveKit  `json:"liveKit"`
	Error       OptString      `json:"error"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   OptDateTime    `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Camera) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *Camera) GetDisplayName() string {
	return s.DisplayName
}

// GetProtocol returns the value of Protocol.
func (s *Camera) GetProtocol() CameraProtocol {
	return s.Protocol
}

// GetPhase returns the value of Phase.
func (s *Camera) GetPhase() CameraPhase {
	return s.Phase
}

// GetEndpoint returns the value of Endpoint.
func (s *Camera) GetEndpoint() CameraEndpoint {
	return s.Endpoint
}

// GetLiveKit returns the value of LiveKit.
func (s *Camera) GetLiveKit() CameraLiveKit {
	return s.LiveKit
}

// GetError returns the value of Error.
func (s *Camera) GetError() OptString {
	return s.Error
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Camera) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Camera) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Camera) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Camera) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetProtocol sets the value of Protocol.
func (s *Camera) SetProtocol(val CameraProtocol) {
	s.Protocol = val
}

// SetPhase sets the value of Phase.
func (s *Camera) SetPhase(val CameraPhase) {
	s.Phase = val
}

// SetEndpoint sets the value of Endpoint.
func (s *Camera) SetEndpoint(val CameraEndpoint) {
	s.Endpoint = val
}

// SetLiveKit sets the value of LiveKit.
func (s *Camera) SetLiveKit(val CameraLiveKit) {
	s.LiveKit = val
}

// SetError sets the value of Error.
func (s *Camera) SetError(val OptString) {
	s.Error = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Camera) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Camera) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Camera) createCameraRes() {}
func (*Camera) getCameraRes()    {}

// Ref: #/components/schemas/CameraEndpoint
type CameraEndpoint struct {
	Protocol CameraProtocol `json:"protocol"`
	// URL to configure on the camera.
	URL string `json:"url"`
	// Text payload that the frontend should render as a QR code.
	QrCodeText string `json:"qrCodeText"`
}

// GetProtocol returns the value of Protocol.
func (s *CameraEndpoint) GetProtocol() CameraProtocol {
	return s.Protocol
}

// GetURL returns the value of URL.
func (s *CameraEndpoint) GetURL() string {
	return s.URL
}

// GetQrCodeText returns the value of QrCodeText.
func (s *CameraEndpoint) GetQrCodeText() string {
	return s.QrCodeText
}

// SetProtocol sets the value of Protocol.
func (s *CameraEndpoint) SetProtocol(val CameraProtocol) {
	s.Protocol = val
}

// SetURL sets the value of URL.
func (s *CameraEndpoint) SetURL(val string) {
	s.URL = val
}

// SetQrCodeText sets the value of QrCodeText.
func (s *CameraEndpoint) SetQrCodeText(val string) {
	s.QrCodeText = val
}

func (*CameraEndpoint) getCameraEndpointRes() {}

// Ref: #/components/schemas/CameraList
type CameraList struct {
	Items []Camera `json:"items"`
}

// GetItems returns the value of Items.
func (s *CameraList) GetItems() []Camera {
	return s.Items
}

// SetItems sets the value of Items.
func (s *CameraList) SetItems(val []Camera) {
	s.Items = val
}

// Ref: #/components/schemas/CameraLiveKit
type CameraLiveKit struct {
	Room                string    `json:"room"`
	Connected           bool      `json:"connected"`
	ParticipantIdentity OptString `json:"participantIdentity"`
	ParticipantName     OptString `json:"participantName"`
}

// GetRoom returns the value of Room.
func (s *CameraLiveKit) GetRoom() string {
	return s.Room
}

// GetConnected returns the value of Connected.
func (s *CameraLiveKit) GetConnected() bool {
	return s.Connected
}

// GetParticipantIdentity returns the value of ParticipantIdentity.
func (s *CameraLiveKit) GetParticipantIdentity() OptString {
	return s.ParticipantIdentity
}

// GetParticipantName returns the value of ParticipantName.
func (s *CameraLiveKit) GetParticipantName() OptString {
	return s.ParticipantName
}

// SetRoom sets the value of Room.
func (s *CameraLiveKit) SetRoom(val string) {
	s.Room = val
}

// SetConnected sets the value of Connected.
func (s *CameraLiveKit) SetConnected(val bool) {
	s.Connected = val
}

// SetParticipantIdentity sets the value of ParticipantIdentity.
func (s *CameraLiveKit) SetParticipantIdentity(val OptString) {
	s.ParticipantIdentity = val
}

// SetParticipantName sets the value of ParticipantName.
func (s *CameraLiveKit) SetParticipantName(val OptString) {
	s.ParticipantName = val
}

// Ref: #/components/schemas/CameraPhase
type CameraPhase string

const (
	CameraPhasePending  CameraPhase = "pending"
	CameraPhaseReady    CameraPhase = "ready"
	CameraPhaseDegraded CameraPhase = "degraded"
	CameraPhaseFailed   CameraPhase = "failed"
)

// AllValues returns all CameraPhase values.
func (CameraPhase) AllValues() []CameraPhase {
	return []CameraPhase{
		CameraPhasePending,
		CameraPhaseReady,
		CameraPhaseDegraded,
		CameraPhaseFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CameraPhase) MarshalText() ([]byte, error) {
	switch s {
	case CameraPhasePending:
		return []byte(s), nil
	case CameraPhaseReady:
		return []byte(s), nil
	case CameraPhaseDegraded:
		return []byte(s), nil
	case CameraPhaseFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CameraPhase) UnmarshalText(data []byte) error {
	switch CameraPhase(data) {
	case CameraPhasePending:
		*s = CameraPhasePending
		return nil
	case CameraPhaseReady:
		*s = CameraPhaseReady
		return nil
	case CameraPhaseDegraded:
		*s = CameraPhaseDegraded
		return nil
	case CameraPhaseFailed:
		*s = CameraPhaseFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CameraProtocol
type CameraProtocol string

const (
	CameraProtocolSrt  CameraProtocol = "srt"
	CameraProtocolRist CameraProtocol = "rist"
)

// AllValues returns all CameraProtocol values.
func (CameraProtocol) AllValues() []CameraProtocol {
	return []CameraProtocol{
		CameraProtocolSrt,
		CameraProtocolRist,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CameraProtocol) MarshalText() ([]byte, error) {
	switch s {
	case CameraProtocolSrt:
		return []byte(s), nil
	case CameraProtocolRist:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CameraProtocol) UnmarshalText(data []byte) error {
	switch CameraProtocol(data) {
	case CameraProtocolSrt:
		*s = CameraProtocolSrt
		return nil
	case CameraProtocolRist:
		*s = CameraProtocolRist
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateCameraBadRequest Error

func (*CreateCameraBadRequest) createCameraRes() {}

type CreateCameraConflict Error

func (*CreateCameraConflict) createCameraRes() {}

// Ref: #/components/schemas/CreateCameraRequest
type CreateCameraRequest struct {
	DisplayName string         `json:"displayName"`
	Protocol    CameraProtocol `json:"protocol"`
	LiveKitRoom OptString      `json:"liveKitRoom"`
}

// GetDisplayName returns the value of DisplayName.
func (s *CreateCameraRequest) GetDisplayName() string {
	return s.DisplayName
}

// GetProtocol returns the value of Protocol.
func (s *CreateCameraRequest) GetProtocol() CameraProtocol {
	return s.Protocol
}

// GetLiveKitRoom returns the value of LiveKitRoom.
func (s *CreateCameraRequest) GetLiveKitRoom() OptString {
	return s.LiveKitRoom
}

// SetDisplayName sets the value of DisplayName.
func (s *CreateCameraRequest) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetProtocol sets the value of Protocol.
func (s *CreateCameraRequest) SetProtocol(val CameraProtocol) {
	s.Protocol = val
}

// SetLiveKitRoom sets the value of LiveKitRoom.
func (s *CreateCameraRequest) SetLiveKitRoom(val OptString) {
	s.LiveKitRoom = val
}

type DeleteCameraConflict Error

func (*DeleteCameraConflict) deleteCameraRes() {}

// DeleteCameraNoContent is response for DeleteCamera operation.
type DeleteCameraNoContent struct{}

func (*DeleteCameraNoContent) deleteCameraRes() {}

type DeleteCameraNotFound Error

func (*DeleteCameraNotFound) deleteCameraRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getCameraEndpointRes()    {}
func (*Error) getCameraRes()            {}
func (*Error) getLiveKitConnectionRes() {}
func (*Error) getTakeRes()              {}

type GetHealthzOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetHealthzOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// Ref: #/components/schemas/LiveKitConnection
type LiveKitConnection struct {
	URL                 string    `json:"url"`
	Room                string    `json:"room"`
	Token               string    `json:"token"`
	ParticipantIdentity string    `json:"participantIdentity"`
	ParticipantName     OptString `json:"participantName"`
}

// GetURL returns the value of URL.
func (s *LiveKitConnection) GetURL() string {
	return s.URL
}

// GetRoom returns the value of Room.
func (s *LiveKitConnection) GetRoom() string {
	return s.Room
}

// GetToken returns the value of Token.
func (s *LiveKitConnection) GetToken() string {
	return s.Token
}

// GetParticipantIdentity returns the value of ParticipantIdentity.
func (s *LiveKitConnection) GetParticipantIdentity() string {
	return s.ParticipantIdentity
}

// GetParticipantName returns the value of ParticipantName.
func (s *LiveKitConnection) GetParticipantName() OptString {
	return s.ParticipantName
}

// SetURL sets the value of URL.
func (s *LiveKitConnection) SetURL(val string) {
	s.URL = val
}

// SetRoom sets the value of Room.
func (s *LiveKitConnection) SetRoom(val string) {
	s.Room = val
}

// SetToken sets the value of Token.
func (s *LiveKitConnection) SetToken(val string) {
	s.Token = val
}

// SetParticipantIdentity sets the value of ParticipantIdentity.
func (s *LiveKitConnection) SetParticipantIdentity(val string) {
	s.ParticipantIdentity = val
}

// SetParticipantName sets the value of ParticipantName.
func (s *LiveKitConnection) SetParticipantName(val OptString) {
	s.ParticipantName = val
}

func (*LiveKitConnection) getLiveKitConnectionRes() {}

// Ref: #/components/schemas/LiveKitInfo
type LiveKitInfo struct {
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *LiveKitInfo) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *LiveKitInfo) SetURL(val string) {
	s.URL = val
}

// Ref: #/components/schemas/LiveKitRoom
type LiveKitRoom struct {
	Name      string  `json:"name"`
	CameraId  string  `json:"cameraId"`
	Connected OptBool `json:"connected"`
}

// GetName returns the value of Name.
func (s *LiveKitRoom) GetName() string {
	return s.Name
}

// GetCameraId returns the value of CameraId.
func (s *LiveKitRoom) GetCameraId() string {
	return s.CameraId
}

// GetConnected returns the value of Connected.
func (s *LiveKitRoom) GetConnected() OptBool {
	return s.Connected
}

// SetName sets the value of Name.
func (s *LiveKitRoom) SetName(val string) {
	s.Name = val
}

// SetCameraId sets the value of CameraId.
func (s *LiveKitRoom) SetCameraId(val string) {
	s.CameraId = val
}

// SetConnected sets the value of Connected.
func (s *LiveKitRoom) SetConnected(val OptBool) {
	s.Connected = val
}

// Ref: #/components/schemas/LiveKitRoomList
type LiveKitRoomList struct {
	Items []LiveKitRoom `json:"items"`
}

// GetItems returns the value of Items.
func (s *LiveKitRoomList) GetItems() []LiveKitRoom {
	return s.Items
}

// SetItems sets the value of Items.
func (s *LiveKitRoomList) SetItems(val []LiveKitRoom) {
	s.Items = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCameraProtocol returns new OptCameraProtocol with value set to v.
func NewOptCameraProtocol(v CameraProtocol) OptCameraProtocol {
	return OptCameraProtocol{
		Value: v,
		Set:   true,
	}
}

// OptCameraProtocol is optional CameraProtocol.
type OptCameraProtocol struct {
	Value CameraProtocol
	Set   bool
}

// IsSet returns true if OptCameraProtocol was set.
func (o OptCameraProtocol) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCameraProtocol) Reset() {
	var v CameraProtocol
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCameraProtocol) SetTo(v CameraProtocol) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCameraProtocol) Get() (v CameraProtocol, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCameraProtocol) Or(d CameraProtocol) CameraProtocol {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptStopTakeRequest returns new OptStopTakeRequest with value set to v.
func NewOptStopTakeRequest(v StopTakeRequest) OptStopTakeRequest {
	return OptStopTakeRequest{
		Value: v,
		Set:   true,
	}
}

// OptStopTakeRequest is optional StopTakeRequest.
type OptStopTakeRequest struct {
	Value StopTakeRequest
	Set   bool
}

// IsSet returns true if OptStopTakeRequest was set.
func (o OptStopTakeRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptStopTakeRequest) Reset() {
	var v StopTakeRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptStopTakeRequest) SetTo(v StopTakeRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptStopTakeRequest) Get() (v StopTakeRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptStopTakeRequest) Or(d StopTakeRequest) StopTakeRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTakePhase returns new OptTakePhase with value set to v.
func NewOptTakePhase(v TakePhase) OptTakePhase {
	return OptTakePhase{
		Value: v,
		Set:   true,
	}
}

// OptTakePhase is optional TakePhase.
type OptTakePhase struct {
	Value TakePhase
	Set   bool
}

// IsSet returns true if OptTakePhase was set.
func (o OptTakePhase) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTakePhase) Reset() {
	var v TakePhase
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTakePhase) SetTo(v TakePhase) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTakePhase) Get() (v TakePhase, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTakePhase) Or(d TakePhase) TakePhase {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/S3Output
type S3Output struct {
	Bucket    string    `json:"bucket"`
	ObjectKey string    `json:"objectKey"`
	URI       OptString `json:"uri"`
	Endpoint  OptString `json:"endpoint"`
	Region    OptString `json:"region"`
}

// GetBucket returns the value of Bucket.
func (s *S3Output) GetBucket() string {
	return s.Bucket
}

// GetObjectKey returns the value of ObjectKey.
func (s *S3Output) GetObjectKey() string {
	return s.ObjectKey
}

// GetURI returns the value of URI.
func (s *S3Output) GetURI() OptString {
	return s.URI
}

// GetEndpoint returns the value of Endpoint.
func (s *S3Output) GetEndpoint() OptString {
	return s.Endpoint
}

// GetRegion returns the value of Region.
func (s *S3Output) GetRegion() OptString {
	return s.Region
}

// SetBucket sets the value of Bucket.
func (s *S3Output) SetBucket(val string) {
	s.Bucket = val
}

// SetObjectKey sets the value of ObjectKey.
func (s *S3Output) SetObjectKey(val string) {
	s.ObjectKey = val
}

// SetURI sets the value of URI.
func (s *S3Output) SetURI(val OptString) {
	s.URI = val
}

// SetEndpoint sets the value of Endpoint.
func (s *S3Output) SetEndpoint(val OptString) {
	s.Endpoint = val
}

// SetRegion sets the value of Region.
func (s *S3Output) SetRegion(val OptString) {
	s.Region = val
}

// Ref: #/components/schemas/S3OutputRequest
type S3OutputRequest struct {
	Bucket string `json:"bucket"`
	// If omitted, the server allocates an object key.
	ObjectKey OptString `json:"objectKey"`
	Endpoint  OptString `json:"endpoint"`
	Region    OptString `json:"region"`
}

// GetBucket returns the value of Bucket.
func (s *S3OutputRequest) GetBucket() string {
	return s.Bucket
}

// GetObjectKey returns the value of ObjectKey.
func (s *S3OutputRequest) GetObjectKey() OptString {
	return s.ObjectKey
}

// GetEndpoint returns the value of Endpoint.
func (s *S3OutputRequest) GetEndpoint() OptString {
	return s.Endpoint
}

// GetRegion returns the value of Region.
func (s *S3OutputRequest) GetRegion() OptString {
	return s.Region
}

// SetBucket sets the value of Bucket.
func (s *S3OutputRequest) SetBucket(val string) {
	s.Bucket = val
}

// SetObjectKey sets the value of ObjectKey.
func (s *S3OutputRequest) SetObjectKey(val OptString) {
	s.ObjectKey = val
}

// SetEndpoint sets the value of Endpoint.
func (s *S3OutputRequest) SetEndpoint(val OptString) {
	s.Endpoint = val
}

// SetRegion sets the value of Region.
func (s *S3OutputRequest) SetRegion(val OptString) {
	s.Region = val
}

type StartTakeBadRequest Error

func (*StartTakeBadRequest) startTakeRes() {}

type StartTakeConflict Error

func (*StartTakeConflict) startTakeRes() {}

type StartTakeNotFound Error

func (*StartTakeNotFound) startTakeRes() {}

// Ref: #/components/schemas/StartTakeRequest
type StartTakeRequest struct {
	CameraId string            `json:"cameraId"`
	Output   TakeOutputRequest `json:"output"`
}

// GetCameraId returns the value of CameraId.
func (s *StartTakeRequest) GetCameraId() string {
	return s.CameraId
}

// GetOutput returns the value of Output.
func (s *StartTakeRequest) GetOutput() TakeOutputRequest {
	return s.Output
}

// SetCameraId sets the value of CameraId.
func (s *StartTakeRequest) SetCameraId(val string) {
	s.CameraId = val
}

// SetOutput sets the value of Output.
func (s *StartTakeRequest) SetOutput(val TakeOutputRequest) {
	s.Output = val
}

type StopTakeConflict Error

func (*StopTakeConflict) stopTakeRes() {}

type StopTakeNotFound Error

func (*StopTakeNotFound) stopTakeRes() {}

// Ref: #/components/schemas/StopTakeRequest
type StopTakeRequest struct {
	RequestedAt OptDateTime `json:"requestedAt"`
}

// GetRequestedAt returns the value of RequestedAt.
func (s *StopTakeRequest) GetRequestedAt() OptDateTime {
	return s.RequestedAt
}

// SetRequestedAt sets the value of RequestedAt.
func (s *StopTakeRequest) SetRequestedAt(val OptDateTime) {
	s.RequestedAt = val
}

// Ref: #/components/schemas/Take
type Take struct {
	ID              string      `json:"id"`
	CameraId        string      `json:"cameraId"`
	Phase           TakePhase   `json:"phase"`
	Output          TakeOutput  `json:"output"`
	StartedAt       OptDateTime `json:"startedAt"`
	StopRequestedAt OptDateTime `json:"stopRequestedAt"`
	StoppedAt       OptDateTime `json:"stoppedAt"`
	CompletedAt     OptDateTime `json:"completedAt"`
	Error           OptString   `json:"error"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       OptDateTime `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Take) GetID() string {
	return s.ID
}

// GetCameraId returns the value of CameraId.
func (s *Take) GetCameraId() string {
	return s.CameraId
}

// GetPhase returns the value of Phase.
func (s *Take) GetPhase() TakePhase {
	return s.Phase
}

// GetOutput returns the value of Output.
func (s *Take) GetOutput() TakeOutput {
	return s.Output
}

// GetStartedAt returns the value of StartedAt.
func (s *Take) GetStartedAt() OptDateTime {
	return s.StartedAt
}

// GetStopRequestedAt returns the value of StopRequestedAt.
func (s *Take) GetStopRequestedAt() OptDateTime {
	return s.StopRequestedAt
}

// GetStoppedAt returns the value of StoppedAt.
func (s *Take) GetStoppedAt() OptDateTime {
	return s.StoppedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *Take) GetCompletedAt() OptDateTime {
	return s.CompletedAt
}

// GetError returns the value of Error.
func (s *Take) GetError() OptString {
	return s.Error
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Take) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Take) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Take) SetID(val string) {
	s.ID = val
}

// SetCameraId sets the value of CameraId.
func (s *Take) SetCameraId(val string) {
	s.CameraId = val
}

// SetPhase sets the value of Phase.
func (s *Take) SetPhase(val TakePhase) {
	s.Phase = val
}

// SetOutput sets the value of Output.
func (s *Take) SetOutput(val TakeOutput) {
	s.Output = val
}

// SetStartedAt sets the value of StartedAt.
func (s *Take) SetStartedAt(val OptDateTime) {
	s.StartedAt = val
}

// SetStopRequestedAt sets the value of StopRequestedAt.
func (s *Take) SetStopRequestedAt(val OptDateTime) {
	s.StopRequestedAt = val
}

// SetStoppedAt sets the value of StoppedAt.
func (s *Take) SetStoppedAt(val OptDateTime) {
	s.StoppedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *Take) SetCompletedAt(val OptDateTime) {
	s.CompletedAt = val
}

// SetError sets the value of Error.
func (s *Take) SetError(val OptString) {
	s.Error = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Take) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Take) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Take) getTakeRes()   {}
func (*Take) startTakeRes() {}
func (*Take) stopTakeRes()  {}

// Ref: #/components/schemas/TakeList
type TakeList struct {
	Items []Take `json:"items"`
}

// GetItems returns the value of Items.
func (s *TakeList) GetItems() []Take {
	return s.Items
}

// SetItems sets the value of Items.
func (s *TakeList) SetItems(val []Take) {
	s.Items = val
}

// Ref: #/components/schemas/TakeOutput
type TakeOutput struct {
	S3 S3Output `json:"s3"`
}

// GetS3 returns the value of S3.
func (s *TakeOutput) GetS3() S3Output {
	return s.S3
}

// SetS3 sets the value of S3.
func (s *TakeOutput) SetS3(val S3Output) {
	s.S3 = val
}

// Ref: #/components/schemas/TakeOutputRequest
type TakeOutputRequest struct {
	S3 S3OutputRequest `json:"s3"`
}

// GetS3 returns the value of S3.
func (s *TakeOutputRequest) GetS3() S3OutputRequest {
	return s.S3
}

// SetS3 sets the value of S3.
func (s *TakeOutputRequest) SetS3(val S3OutputRequest) {
	s.S3 = val
}

// Ref: #/components/schemas/TakePhase
type TakePhase string

const (
	TakePhasePending       TakePhase = "pending"
	TakePhaseCapturing     TakePhase = "capturing"
	TakePhaseStopRequested TakePhase = "stop_requested"
	TakePhaseUploading     TakePhase = "uploading"
	TakePhaseCompleted     TakePhase = "completed"
	TakePhaseFailed        TakePhase = "failed"
)

// AllValues returns all TakePhase values.
func (TakePhase) AllValues() []TakePhase {
	return []TakePhase{
		TakePhasePending,
		TakePhaseCapturing,
		TakePhaseStopRequested,
		TakePhaseUploading,
		TakePhaseCompleted,
		TakePhaseFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TakePhase) MarshalText() ([]byte, error) {
	switch s {
	case TakePhasePending:
		return []byte(s), nil
	case TakePhaseCapturing:
		return []byte(s), nil
	case TakePhaseStopRequested:
		return []byte(s), nil
	case TakePhaseUploading:
		return []byte(s), nil
	case TakePhaseCompleted:
		return []byte(s), nil
	case TakePhaseFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TakePhase) UnmarshalText(data []byte) error {
	switch TakePhase(data) {
	case TakePhasePending:
		*s = TakePhasePending
		return nil
	case TakePhaseCapturing:
		*s = TakePhaseCapturing
		return nil
	case TakePhaseStopRequested:
		*s = TakePhaseStopRequested
		return nil
	case TakePhaseUploading:
		*s = TakePhaseUploading
		return nil
	case TakePhaseCompleted:
		*s = TakePhaseCompleted
		return nil
	case TakePhaseFailed:
		*s = TakePhaseFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
