// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateCamera implements createCamera operation.
	//
	// Add a camera ingest endpoint.
	//
	// POST /cameras
	CreateCamera(ctx context.Context, req *CreateCameraRequest) (CreateCameraRes, error)
	// DeleteCamera implements deleteCamera operation.
	//
	// Delete a camera ingest endpoint.
	//
	// DELETE /cameras/{cameraId}
	DeleteCamera(ctx context.Context, params DeleteCameraParams) (DeleteCameraRes, error)
	// GetCamera implements getCamera operation.
	//
	// Get a camera.
	//
	// GET /cameras/{cameraId}
	GetCamera(ctx context.Context, params GetCameraParams) (GetCameraRes, error)
	// GetCameraEndpoint implements getCameraEndpoint operation.
	//
	// Returns the URL that the frontend can render as a QR code for camera setup.
	//
	// GET /cameras/{cameraId}/endpoint
	GetCameraEndpoint(ctx context.Context, params GetCameraEndpointParams) (GetCameraEndpointRes, error)
	// GetHealthz implements getHealthz operation.
	//
	// Health check.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (GetHealthzOK, error)
	// GetLiveKitConnection implements getLiveKitConnection operation.
	//
	// Get LiveKit connection details.
	//
	// GET /livekit/rooms/{roomName}/connection
	GetLiveKitConnection(ctx context.Context, params GetLiveKitConnectionParams) (GetLiveKitConnectionRes, error)
	// GetLiveKitInfo implements getLiveKitInfo operation.
	//
	// Get LiveKit service information.
	//
	// GET /livekit
	GetLiveKitInfo(ctx context.Context) (*LiveKitInfo, error)
	// GetTake implements getTake operation.
	//
	// Get a take.
	//
	// GET /takes/{takeId}
	GetTake(ctx context.Context, params GetTakeParams) (GetTakeRes, error)
	// ListCameras implements listCameras operation.
	//
	// List cameras.
	//
	// GET /cameras
	ListCameras(ctx context.Context, params ListCamerasParams) (*CameraList, error)
	// ListLiveKitRooms implements listLiveKitRooms operation.
	//
	// List LiveKit rooms used by cameras.
	//
	// GET /livekit/rooms
	ListLiveKitRooms(ctx context.Context) (*LiveKitRoomList, error)
	// ListTakes implements listTakes operation.
	//
	// List takes.
	//
	// GET /takes
	ListTakes(ctx context.Context, params ListTakesParams) (*TakeList, error)
	// StartTake implements startTake operation.
	//
	// Start a take.
	//
	// POST /takes
	StartTake(ctx context.Context, req *StartTakeRequest) (StartTakeRes, error)
	// StopTake implements stopTake operation.
	//
	// Stop a take.
	//
	// POST /takes/{takeId}/stop
	StopTake(ctx context.Context, req OptStopTakeRequest, params StopTakeParams) (StopTakeRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
