// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateCamera implements createCamera operation.
//
// Add a camera ingest endpoint.
//
// POST /cameras
func (UnimplementedHandler) CreateCamera(ctx context.Context, req *CreateCameraRequest) (r CreateCameraRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCamera implements deleteCamera operation.
//
// Delete a camera ingest endpoint.
//
// DELETE /cameras/{cameraId}
func (UnimplementedHandler) DeleteCamera(ctx context.Context, params DeleteCameraParams) (r DeleteCameraRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCamera implements getCamera operation.
//
// Get a camera.
//
// GET /cameras/{cameraId}
func (UnimplementedHandler) GetCamera(ctx context.Context, params GetCameraParams) (r GetCameraRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCameraEndpoint implements getCameraEndpoint operation.
//
// Returns the URL that the frontend can render as a QR code for camera setup.
//
// GET /cameras/{cameraId}/endpoint
func (UnimplementedHandler) GetCameraEndpoint(ctx context.Context, params GetCameraEndpointParams) (r GetCameraEndpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthz implements getHealthz operation.
//
// Health check.
//
// GET /healthz
func (UnimplementedHandler) GetHealthz(ctx context.Context) (r GetHealthzOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLiveKitConnection implements getLiveKitConnection operation.
//
// Get LiveKit connection details.
//
// GET /livekit/rooms/{roomName}/connection
func (UnimplementedHandler) GetLiveKitConnection(ctx context.Context, params GetLiveKitConnectionParams) (r GetLiveKitConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLiveKitInfo implements getLiveKitInfo operation.
//
// Get LiveKit service information.
//
// GET /livekit
func (UnimplementedHandler) GetLiveKitInfo(ctx context.Context) (r *LiveKitInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTake implements getTake operation.
//
// Get a take.
//
// GET /takes/{takeId}
func (UnimplementedHandler) GetTake(ctx context.Context, params GetTakeParams) (r GetTakeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCameras implements listCameras operation.
//
// List cameras.
//
// GET /cameras
func (UnimplementedHandler) ListCameras(ctx context.Context, params ListCamerasParams) (r *CameraList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListLiveKitRooms implements listLiveKitRooms operation.
//
// List LiveKit rooms used by cameras.
//
// GET /livekit/rooms
func (UnimplementedHandler) ListLiveKitRooms(ctx context.Context) (r *LiveKitRoomList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTakes implements listTakes operation.
//
// List takes.
//
// GET /takes
func (UnimplementedHandler) ListTakes(ctx context.Context, params ListTakesParams) (r *TakeList, _ error) {
	return r, ht.ErrNotImplemented
}

// StartTake implements startTake operation.
//
// Start a take.
//
// POST /takes
func (UnimplementedHandler) StartTake(ctx context.Context, req *StartTakeRequest) (r StartTakeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StopTake implements stopTake operation.
//
// Stop a take.
//
// POST /takes/{takeId}/stop
func (UnimplementedHandler) StopTake(ctx context.Context, req OptStopTakeRequest, params StopTakeParams) (r StopTakeRes, _ error) {
	return r, ht.ErrNotImplemented
}
