// Code generated by ogen, DO NOT EDIT.
package api

type CreateCameraRes interface {
	createCameraRes()
}

type DeleteCameraRes interface {
	deleteCameraRes()
}

type GetCameraEndpointRes interface {
	getCameraEndpointRes()
}

type GetCameraRes interface {
	getCameraRes()
}

type GetLiveKitConnectionRes interface {
	getLiveKitConnectionRes()
}

type GetTakeRes interface {
	getTakeRes()
}

type StartTakeRes interface {
	startTakeRes()
}

type StopTakeRes interface {
	stopTakeRes()
}
