// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteCameraParams is parameters of deleteCamera operation.
type DeleteCameraParams struct {
	CameraId string
}

func unpackDeleteCameraParams(packed middleware.Parameters) (params DeleteCameraParams) {
	{
		key := middleware.ParameterKey{
			Name: "cameraId",
			In:   "path",
		}
		params.CameraId = packed[key].(string)
	}
	return params
}

func decodeDeleteCameraParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteCameraParams, _ error) {
	// Decode path: cameraId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cameraId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CameraId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.CameraId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cameraId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCameraParams is parameters of getCamera operation.
type GetCameraParams struct {
	CameraId string
}

func unpackGetCameraParams(packed middleware.Parameters) (params GetCameraParams) {
	{
		key := middleware.ParameterKey{
			Name: "cameraId",
			In:   "path",
		}
		params.CameraId = packed[key].(string)
	}
	return params
}

func decodeGetCameraParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCameraParams, _ error) {
	// Decode path: cameraId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cameraId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CameraId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.CameraId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cameraId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCameraEndpointParams is parameters of getCameraEndpoint operation.
type GetCameraEndpointParams struct {
	CameraId string
}

func unpackGetCameraEndpointParams(packed middleware.Parameters) (params GetCameraEndpointParams) {
	{
		key := middleware.ParameterKey{
			Name: "cameraId",
			In:   "path",
		}
		params.CameraId = packed[key].(string)
	}
	return params
}

func decodeGetCameraEndpointParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCameraEndpointParams, _ error) {
	// Decode path: cameraId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cameraId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CameraId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.CameraId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cameraId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetLiveKitConnectionParams is parameters of getLiveKitConnection operation.
type GetLiveKitConnectionParams struct {
	RoomName            string
	ParticipantIdentity OptString `json:",omitempty,omitzero"`
	ParticipantName     OptString `json:",omitempty,omitzero"`
}

func unpackGetLiveKitConnectionParams(packed middleware.Parameters) (params GetLiveKitConnectionParams) {
	{
		key := middleware.ParameterKey{
			Name: "roomName",
			In:   "path",
		}
		params.RoomName = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "participantIdentity",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ParticipantIdentity = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "participantName",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ParticipantName = v.(OptString)
		}
	}
	return params
}

func decodeGetLiveKitConnectionParams(args [1]string, argsEscaped bool, r *http.Request) (params GetLiveKitConnectionParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: roomName.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roomName",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.RoomName = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.RoomName)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roomName",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: participantIdentity.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "participantIdentity",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotParticipantIdentityVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotParticipantIdentityVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ParticipantIdentity.SetTo(paramsDotParticipantIdentityVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "participantIdentity",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: participantName.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "participantName",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotParticipantNameVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotParticipantNameVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ParticipantName.SetTo(paramsDotParticipantNameVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "participantName",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetTakeParams is parameters of getTake operation.
type GetTakeParams struct {
	TakeId string
}

func unpackGetTakeParams(packed middleware.Parameters) (params GetTakeParams) {
	{
		key := middleware.ParameterKey{
			Name: "takeId",
			In:   "path",
		}
		params.TakeId = packed[key].(string)
	}
	return params
}

func decodeGetTakeParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTakeParams, _ error) {
	// Decode path: takeId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "takeId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TakeId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.TakeId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "takeId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListCamerasParams is parameters of listCameras operation.
type ListCamerasParams struct {
	Protocol OptCameraProtocol `json:",omitempty,omitzero"`
}

func unpackListCamerasParams(packed middleware.Parameters) (params ListCamerasParams) {
	{
		key := middleware.ParameterKey{
			Name: "protocol",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Protocol = v.(OptCameraProtocol)
		}
	}
	return params
}

func decodeListCamerasParams(args [0]string, argsEscaped bool, r *http.Request) (params ListCamerasParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: protocol.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "protocol",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotProtocolVal CameraProtocol
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotProtocolVal = CameraProtocol(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Protocol.SetTo(paramsDotProtocolVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Protocol.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "protocol",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListTakesParams is parameters of listTakes operation.
type ListTakesParams struct {
	CameraId OptString    `json:",omitempty,omitzero"`
	Phase    OptTakePhase `json:",omitempty,omitzero"`
}

func unpackListTakesParams(packed middleware.Parameters) (params ListTakesParams) {
	{
		key := middleware.ParameterKey{
			Name: "cameraId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CameraId = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "phase",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Phase = v.(OptTakePhase)
		}
	}
	return params
}

func decodeListTakesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListTakesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cameraId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cameraId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCameraIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCameraIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CameraId.SetTo(paramsDotCameraIdVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cameraId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: phase.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "phase",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPhaseVal TakePhase
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotPhaseVal = TakePhase(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Phase.SetTo(paramsDotPhaseVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Phase.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "phase",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// StopTakeParams is parameters of stopTake operation.
type StopTakeParams struct {
	TakeId string
}

func unpackStopTakeParams(packed middleware.Parameters) (params StopTakeParams) {
	{
		key := middleware.ParameterKey{
			Name: "takeId",
			In:   "path",
		}
		params.TakeId = packed[key].(string)
	}
	return params
}

func decodeStopTakeParams(args [1]string, argsEscaped bool, r *http.Request) (params StopTakeParams, _ error) {
	// Decode path: takeId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "takeId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TakeId = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.TakeId)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "takeId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
