// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCameraOperation         OperationName = "CreateCamera"
	DeleteCameraOperation         OperationName = "DeleteCamera"
	GetCameraOperation            OperationName = "GetCamera"
	GetCameraEndpointOperation    OperationName = "GetCameraEndpoint"
	GetHealthzOperation           OperationName = "GetHealthz"
	GetLiveKitConnectionOperation OperationName = "GetLiveKitConnection"
	GetLiveKitInfoOperation       OperationName = "GetLiveKitInfo"
	GetTakeOperation              OperationName = "GetTake"
	ListCamerasOperation          OperationName = "ListCameras"
	ListLiveKitRoomsOperation     OperationName = "ListLiveKitRooms"
	ListTakesOperation            OperationName = "ListTakes"
	StartTakeOperation            OperationName = "StartTake"
	StopTakeOperation             OperationName = "StopTake"
)
