log_level: info

api_key: devkey
api_secret: devsecretdevsecretdevsecretdevsecret
ws_url: ws://livekit:7880

redis:
  address: redis:6379

rtmp_port: 1935
whip_port: 8080
health_port: 8081

rtc_config:
  udp_port: 7885
  use_external_ip: false
