apiVersion: recording.kinugasa.dev/v1alpha1
kind: Stream
metadata:
  name: studio-rist
spec:
  input:
    protocol: rist
    uri: rist://@:9001
    port: 9001
    nodePort: 30901
  livekit:
    room: studio-rist
  take:
    protocol: srt
    port: 10000
