apiVersion: recording.kinugasa.dev/v1alpha1
kind: Stream
metadata:
  name: studio-a
spec:
  input:
    protocol: srt
    uri: srt://:9000?mode=listener
    port: 9000
    nodePort: 30900
  livekit:
    room: studio-a
  take:
    protocol: srt
    port: 10000
