name: Format Check

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: DeterminateSystems/nix-installer-action@main
            - uses: DeterminateSystems/magic-nix-cache-action@main
            - run: nix run .#ci:treefmt:check
